default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user_name
  password: mysql_password
  host: db

development:
  <<: *default
  database: db_name

test:
  <<: *default
  database: app_test
